fstab_nfs_mounts:
  - src: "192.168.14.27:/f04-base_old"
    dest: "/mnt/share/f04-base_old"
  - src: "192.168.14.27:/f04-cd_rec"
    dest: "/mnt/share/f04-cd_rec"
  - src: "192.168.14.27:/f04-exchange"
    dest: "/mnt/share/f04-exchange"
  - src: "192.168.14.27:/f04-exchenge"
    dest: "/mnt/share/f04-exchenge"
  - src: "192.168.14.27:/f04-exchenge1"
    dest: "/mnt/share/f04-exchenge1"
  - src: "192.168.14.27:/f04-hallmusic"
    dest: "/mnt/share/f04-hallmusic"
  - src: "192.168.14.27:/f04-infodent"
    dest: "/mnt/share/f04-infodent"
  - src: "192.168.14.27:/f04-k_photo"
    dest: "/mnt/share/f04-k_photo"
  - src: "192.168.14.27:/f04-kt"
    dest: "/mnt/share/f04-kt"
  - src: "192.168.14.27:/f04-logs"
    dest: "/mnt/share/f04-logs"
  - src: "192.168.14.27:/f04-media-upr"
    dest: "/mnt/share/f04-media-upr"
  - src: "192.168.14.27:/f04-narko"
    dest: "/mnt/share/f04-narko"
  - src: "192.168.14.27:/f04-obmen"
    dest: "/mnt/share/f04-obmen"
  - src: "192.168.14.27:/f04-photo"
    dest: "/mnt/share/f04-photo"
  - src: "192.168.14.27:/f04-scan"
    dest: "/mnt/share/f04-scan"
  - src: "192.168.14.27:/f04-stomat"
    dest: "/mnt/share/f04-stomat"
  - src: "192.168.14.27:/f04-tw"
    dest: "/mnt/share/f04-tw"
  - src: "192.168.14.27:/f04-ucheba"
    dest: "/mnt/share/f04-ucheba"